# Generated by Django 6.0.3 on 2026-04-08 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_comment_post_created_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                condition=models.Q(("is_approved", True)),
                fields=["post"],
                name="blog_comment_post_approved_idx",
            ),
        ),
    ]
