# Generated by Django 6.0.3 on 2026-04-08 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_add_comment_post_approved_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                condition=models.Q(("status", "published")),
                fields=["author"],
                name="blog_post_author_published_idx",
            ),
        ),
    ]
